.TH nova\-compute 8
.SH NAME
nova\-network \- provides network ressources (connectivity and IP addresses)

.SH SYNOPSIS
.B nova-compute
.B \-\-flagfile=<flagfilepath>

.SH DESCRIPTION
.B nova-network

This man page is a stub. Please contribute.

.SH PARAMETERS

.LP
.B \-\-flagfile=<flagfilepath>
.IP

Path to the file containing options.
