.TH nova\-volume 8
.SH NAME
nova\-volume \- provides EBS like storage for your virtual machine instances

.SH SYNOPSIS
.B nova\-volume
.B \-\-flagfile=<flagfilepath>

.SH DESCRIPTION
.B nova\-volume

Nova-volume provides storage for your virtual machine instances.
These could be a partition on your VM, and can be a persistent storage.
This man page is a stub. Please contribute.

.SH PARAMETERS

.LP
.B \-\-flagfile=<flagfilepath>
.IP

Path to the file containing options.
