.TH nova\-vncproxy 8
.SH NAME
nova\-vncproxy \- nova VNC console proxy

.SH SYNOPSIS
.B nova\-vncproxy
.B \-\-flagfile=<flagfilepath>

.SH DESCRIPTION
.B nova\-vncproxy

This man page is a stub. Please contribute.

.SH PARAMETERS

.LP
.B \-\-flagfile=<flagfilepath>
.IP

Path to the file containing options.
