.TH nova\-objectstore 8
.SH NAME
nova\-objectstore \- provides virtual machine storage functionalities

.SH SYNOPSIS
.B nova-objectstore
.B \-\-flagfile=<flagfilepath>

.SH DESCRIPTION
.B nova\-objectstore

This man page is a stub. Please contribute.

.SH PARAMETERS

.LP
.B \-\-flagfile=<flagfilepath>
.IP

Path to the file containing options.
